### PR TITLE
Bugfix/resample

### PR DESCRIPTION
**Pull request by EngieAntoine**

### CODE REVIEW

**Comment by zogzog** [comment]
I'll address this tomorrow.

**Comment by zogzog** [comment]
But I just had a look and it is a  bit sad that Octave did not respect the tests coding conventions (and we already had a discussion about this). This will create unwanted work on my side as I need to be able to understand and debug those tests easily, just as the others.

**Comment by zogzog** [comment]
Ok I did a thorough review of the contribution and a few cosmetic changes. Also I've written a test (similar to the one in test_resample, which I plan to remove) in test_operators.py
I you agree on this version, I'll keep it just without the original tests.
See https://github.com/pythonianfr/tshistory_formula/commit/449dd06fa6fddc568e6ab3ac036fef4f9af50807 (better-resample branch).

**Comment by zogzog** [comment]
Ok I've integrated this into 0.13.1

**Comment by EngieAntoine** [comment]
tks

**Pull request closed without merging**
